# command line: train.py

base_lr: 0.1
batch_size: 64
cl_mode: null
cl_version: V0
config: ./config/uav/joint_vel.yaml
device:
- 0
eval_interval: 5
feeder: feeders.feeder_uav.Feeder
ignore_weights: []
lambda_1: 0.0001
lambda_2: 0.1
log_interval: 100
loss_alpha: 0.8
lr_decay_rate: 0.1
model: model.ske_mixf.Model_lst_4part_uav
model_args:
  cl_mode: null
  graph: graph.uav.Graph
  graph_args:
    labeling_mode: spatial
  head:
  - ViT-B/32
  k: 8
  num_class: 155
  num_person: 2
  num_point: 17
model_saved_name: ''
nesterov: true
num_epoch: 65
num_worker: 32
optimizer: SGD
phase: train
pred_threshold: 0.0
print_log: true
save_epoch: 30
save_interval: 1
save_score: false
seed: 1
show_topk:
- 1
- 5
start_cl_epoch: -1
start_epoch: 0
step:
- 30
- 50
- 60
te_lr_ratio: 1
test_batch_size: 64
test_feeder_args:
  bone: false
  data_path: data/test_joint.npy
  debug: false
  label_path: data/test_label.npy
  p_interval:
  - 0.95
  split: test
  vel: true
  window_size: 64
train_feeder_args:
  bone: false
  data_path: data/train_joint.npy
  debug: false
  label_path: data/train_label.npy
  normalization: false
  p_interval:
  - 0.5
  - 1
  random_choose: false
  random_move: false
  random_rot: true
  random_shift: false
  split: train
  vel: true
  window_size: 64
use_p_map: true
w_cl_loss: 0.1
w_multi_cl_loss:
- 0.1
- 0.2
- 0.5
- 1
warm_up_epoch: 5
weight_decay: 0.0005
weights: null
work_dir: ./work_dir/mixformer/k8_vel
