work_dir: ./work_dir/infogcn/k8_vel

# feeder
feeder: feeders.feeder_uav.Feeder
train_feeder_args:
  data_path: data/train_joint.npy
  label_path: data/train_label.npy
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 256
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: True
  bone: False

test_feeder_args:
  data_path: data/test_joint.npy
  label_path: data/test_label.npy
  split: test
  window_size: 256
  p_interval: [0.95]
  vel: True
  bone: False
  debug: False

# model
model: model.infogcn.Model_lst_4part_uav
model_args:
  num_class: 155
  num_point: 17
  num_person: 2
  graph: graph.uav.Graph
  k: 2
  head: ['ViT-B/32']
  graph_args:
    labeling_mode: 'spatial'
  cl_mode: Null
  
#optim
weight_decay: 0.0005
base_lr: 0.1
lr_decay_rate: 0.1
step: [60, 80]
warm_up_epoch: 5

# training
device: [0]
batch_size: 64 # default 200
test_batch_size: 64 # default 200
num_epoch: 90
nesterov: True
