work_dir: ./work_dir/ctrgcn/k1f

# feeder
feeder: feeders.feeder_uav.Feeder
train_feeder_args:
  data_path: data/new_train_joint.npy
  label_path: data/new_train_label.npy
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 288
  normalization: False
  random_rot: True
  aug: None
  p_interval: [0.5, 1]
  vel: True
  bone: False

test_feeder_args:
  data_path: data/new_predicted_joint.npy
  label_path: data/new_predicted_label.npy
  split: test
  window_size: 288
  p_interval: [0.95]
  vel: True
  bone: False
  debug: False

# model
model: model.ctrgcn.Model_lst_4part_uav_bone
model_args:
  num_class: 155
  num_point: 17
  num_person: 2
  graph: graph.uav.Graph
  k: 1
  head: ['ViT-B/32']
  graph_args:
    labeling_mode: 'spatial'
  cl_mode: Null  

#optim
weight_decay: 0.0004
base_lr: 0.1
lr_decay_rate: 0.1
step: [30,50]
warm_up_epoch: 5

# training
device: [0]
batch_size: 64
test_batch_size: 64
num_epoch: 60
nesterov: True

# loss
loss: LabelSmoothingCrossEntropy
loss_args:
  smoothing: 0.1
  temperature: 1.1
